// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdHSlS-XbNFcb0otOiK1Eq-6kT6Hpyds8',
    appId: '1:559654086191:web:f1f9720643e6e307fa88da',
    messagingSenderId: '559654086191',
    projectId: 'password-manager-f8302',
    authDomain: 'password-manager-f8302.firebaseapp.com',
    storageBucket: 'password-manager-f8302.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeiZIIjyMuJ7l3JNeuej2GoZLvL9PGJ3o',
    appId: '1:559654086191:android:7956953f42935603fa88da',
    messagingSenderId: '559654086191',
    projectId: 'password-manager-f8302',
    storageBucket: 'password-manager-f8302.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvvOQden8uA1nuVHwWKG-EVPYThyBZscA',
    appId: '1:559654086191:ios:a1fc4b8b58584b59fa88da',
    messagingSenderId: '559654086191',
    projectId: 'password-manager-f8302',
    storageBucket: 'password-manager-f8302.appspot.com',
    iosClientId: '559654086191-f3s6hstp3qg2lbalb226mph2fuvspfv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.passwordManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvvOQden8uA1nuVHwWKG-EVPYThyBZscA',
    appId: '1:559654086191:ios:a1fc4b8b58584b59fa88da',
    messagingSenderId: '559654086191',
    projectId: 'password-manager-f8302',
    storageBucket: 'password-manager-f8302.appspot.com',
    iosClientId: '559654086191-f3s6hstp3qg2lbalb226mph2fuvspfv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.passwordManager',
  );
}
