// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRy982ogCgil1hrgvnsc5d9wqPSNB3akc',
    appId: '1:791901174544:web:4532160c1b0a2fcd594395',
    messagingSenderId: '791901174544',
    projectId: 'memorial-app-2d782',
    authDomain: 'memorial-app-2d782.firebaseapp.com',
    storageBucket: 'memorial-app-2d782.appspot.com',
    measurementId: 'G-QW67ECW28T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXP4IJAsfdkCzBmzae_aikl3FReSvgOZo',
    appId: '1:791901174544:android:c32ed46ebe7dac2c594395',
    messagingSenderId: '791901174544',
    projectId: 'memorial-app-2d782',
    storageBucket: 'memorial-app-2d782.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHPj2Z18wbX6osabFjGZowVzRp78TdoaQ',
    appId: '1:791901174544:ios:5c6b6954391ecc1b594395',
    messagingSenderId: '791901174544',
    projectId: 'memorial-app-2d782',
    storageBucket: 'memorial-app-2d782.appspot.com',
    iosClientId: '791901174544-efmikvamc3hp6cvltc5kbai9a0faml0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.memorialApp',
  );
}
